<!DOCTYPE html>
<html>

  <head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>자바스크립트 예외처리</title>
  <meta name="description" content="자바스크립트 예외처리">
  
  <meta name="author" content="vlueviolet">
  <meta name="copyright" content="&copy; vlueviolet 2020">
  

  <!-- External libraries -->
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.9.0/styles/monokai-sublime.min.css">
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css">

  <!-- Favicon and other icons (made with http://www.favicon-generator.org/) -->
  <link rel="shortcut icon" href="/assets/icons/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/assets/icons/favicon.ico" type="image/x-icon">
  <link rel="apple-touch-icon" sizes="57x57" href="/assets/icons/apple-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="/assets/icons/apple-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="/assets/icons/apple-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="/assets/icons/apple-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="/assets/icons/apple-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="/assets/icons/apple-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="/assets/icons/apple-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="/assets/icons/apple-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/apple-icon-180x180.png">
  <link rel="icon" type="image/png" sizes="192x192"  href="/assets/icons/android-icon-192x192.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="96x96" href="/assets/icons/favicon-96x96.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/favicon-16x16.png">
  <link rel="manifest" href="/assets/icons/manifest.json">
  <meta name="msapplication-TileColor" content="#ffffff">
  <meta name="msapplication-TileImage" content="/assets/icons/ms-icon-144x144.png">
  <meta name="theme-color" content="#ffffff">

  
  <!-- Facebook OGP cards -->
  <meta property="og:description" content="자바스크립트 예외처리" />
  <meta property="og:url" content="http://localhost:4000/javascript/2020/02/17/jascript-exception.html">
  <meta property="og:site_name" content="vlueviolet's blog" />
  <meta property="og:title" content="자바스크립트 예외처리" />
  <meta property="og:type" content="website" />
  <meta property="og:image" content="http://localhost:4000/assets/instacode.png" />
  <meta property="og:image:type" content="image/png" />
  <meta property="og:image:width" content="612" />
  <meta property="og:image:height" content="605" />
  

  
  <!-- Twitter: card tags -->
  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="자바스크립트 예외처리">
  <meta name="twitter:description" content="자바스크립트 예외처리">
  <meta name="twitter:image" content="http://localhost:4000/assets/instacode.png">
  <meta name="twitter:url" content="http://localhost:4000/javascript/2020/02/17/jascript-exception.html">
  

  

  <!-- Site styles -->
  <link rel="stylesheet" href="/css/main.css">
  <link rel="canonical" href="http://localhost:4000/javascript/2020/02/17/jascript-exception.html">
	<link rel="alternate" type="application/rss+xml" title="vlueviolet's blog" href="http://localhost:4000/feed.xml" />
	
	<!-- Tooltips -->
	<script type="text/javascript">
		window.tooltips = []
	</script>
</head>


  <body>

    <header class="navigation" role="banner">
  <div class="navigation-wrapper">
    <a href="/" class="logo">
      
      <img src="/assets/logo.png" alt="vlueviolet's blog">
      
    </a>
    <a href="javascript:void(0)" class="navigation-menu-button" id="js-mobile-menu">
      <i class="fa fa-bars"></i>
    </a>
    <nav role="navigation">
      <ul id="js-navigation-menu" class="navigation-menu show">
				
	
	<li class="nav-link"><a href="/about/">About</a>
	

	

	

	
	<li class="nav-link"><a href="/posts/">Posts</a>
	

	
	<li class="nav-link"><a href="/typography/">Typography</a>
	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	


      </ul>
    </nav>
  </div>
</header>


    <div class="page-content">
        <div class="post">

<div class="post-header-container has-cover" style="background-image: url(/assets/instacode.png);">
  <div class="scrim has-cover">
    <header class="post-header">
      <h1 class="title">자바스크립트 예외처리</h1>
      <p class="info">by <strong>vlueviolet</strong></p>
    </header>
  </div>
</div>

<div class="wrapper">



<section class="post-meta">
  <div class="post-date">February 17, 2020</div>
  <div class="post-categories">
  in 
    
    <a href="/category/javascript">Javascript</a>
    
  
  </div>
</section>

<article class="post-content">
  <h1 id="자바스크립트-예외처리">자바스크립트 예외처리</h1>

<ul>
  <li>강사 : 코드종</li>
  <li>링크
    <ul>
      <li><a href="https://www.youtube.com/watch?v=EBmIHrLTVdg">자바스크립트 예외처리 1/4 - 예외란 무엇인가? throw?</a></li>
      <li><a href="https://www.youtube.com/watch?v=wf6AlMj7TFA">자바스크립트 예외처리 2/4 - try catch, Error 객체</a></li>
      <li><a href="https://www.youtube.com/watch?v=RRc_iVHdDKk">자바스크립트 예외처리 3/4 - promise의 catch함수</a></li>
      <li><a href="https://www.youtube.com/watch?v=kngOWhzPHzg&amp;t=616s">자바스크립트 예외처리 4/4 - async/await의 예외</a></li>
    </ul>
  </li>
</ul>

<h2 id="try-catch를-이용한-예외처리">try, catch를 이용한 예외처리</h2>

<p>일반적인 동기적인 코드의 경우, <code class="highlighter-rouge">try</code>, <code class="highlighter-rouge">catch</code>를 이용해 에러상황을 처리할 수 있다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">f2</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">f2 start</span><span class="dl">'</span><span class="p">);</span>
  <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">'</span><span class="s1">에러</span><span class="dl">'</span><span class="p">);</span> <span class="c1">// 해당하는 콜스택 정보가 담김</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">f2 end</span><span class="dl">'</span><span class="p">);</span>
<span class="p">}</span>

<span class="kd">function</span> <span class="nx">f1</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">f1 start</span><span class="dl">'</span><span class="p">);</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="nx">f2</span><span class="p">();</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="c1">// try에서 발생한 에러를 처리함</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
  <span class="p">}</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">f1 end</span><span class="dl">'</span><span class="p">);</span>
<span class="p">}</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">will : f1</span><span class="dl">'</span><span class="p">);</span>
<span class="nx">f1</span><span class="p">();</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">did : f1</span><span class="dl">'</span><span class="p">);</span>
</code></pre></div></div>

<p>결과 화면같이, error를 catch하는 것을 볼 수 있다.</p>

<p><img width="430" alt="" src="https://user-images.githubusercontent.com/26196090/74635781-0fd30800-51aa-11ea-80ae-241818649909.png" /></p>

<h2 id="promise의-예외처리">promise의 예외처리</h2>

<p>비동기적인 코드는 try, catch에서 에러를 잡을 수 없다.
아래 코드와 같이 try 구문에서 에러를 처리하면, <code class="highlighter-rouge">Uncaught</code>를 확인할 수 있다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">try</span> <span class="p">{</span>
  <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div></div>

<p><img width="250" alt="" src="https://user-images.githubusercontent.com/26196090/74635972-6b04fa80-51aa-11ea-8311-8bab5cca7162.png" /></p>

<p>그래서 promise의 예외처리는 try, catch를 사용하는 것이 아니라,<br />
promise의 catch를 이용해야 한다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">).</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><img width="440" alt="" src="https://user-images.githubusercontent.com/26196090/74636250-f7172200-51aa-11ea-9d05-1bf195279259.png" /></p>

<p>promise의 편리함 중에 하나가 chain 형태로 promise 함수를 넣을 수 있다는 것인데,<br />
catch를 연속 chanin으로 하면 어떨까?</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">1st catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">))</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">2nd catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p>2번째가 실행되지 않고, 1번째만 catch가 실행되는 것을 볼 수 있다.</p>

<p><img width="196" alt="" src="https://user-images.githubusercontent.com/26196090/74636768-064a9f80-51ac-11ea-9d26-651967bf5813.png" /></p>

<h3 id="promise의-chain">promise의 chain</h3>

<p>일반적인 change pattern은 모두 같은 객체를 return한다.
object를 통해 return한 객체와 chain1, chain2를 통해 return한 객체가 모두 같은 객체이다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">object</span><span class="p">().</span>
  <span class="p">.</span><span class="nx">chain1</span><span class="p">()</span>
  <span class="p">.</span><span class="nx">chain2</span><span class="p">()</span>
</code></pre></div></div>

<p>하지만, promise의 chain은 첫번째, 두번째 catch의 경우 다른 객체를 리턴한다.<br />
(then도 마찬가지이다.)</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">1st catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">))</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">2nd catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p>wait(3)를 실행했을때 리턴된 promise는 promise의 executor-즉 wait함수의 Promise의 resolve, reject 실행과 관련된 - 실행상태를 나타내는 promise이다.<br />
이 promise에서 예외가 발생했을때 첫번째 catch를 실행시키게 된다.</p>

<p>첫번째 catch를 실행하고 리턴된 promise는 wait(3)과는 전혀 상관이 없고,<br />
첫번째 catch 자체 행동이 제대로 되었는지에 대한 promise이다.</p>

<p>즉, 두번째 catch는 첫번째 catch가 정상적으로 실행되었는지를 나타내는 promise에 걸어둔 catch이다.</p>

<p>실행을 정리하면 다음과 같다.</p>

<ol>
  <li>wait(3)을 실행하여 첫번째 catch가 실행하였고</li>
  <li>첫번째 catch가 잘 실행하였기 때문에 두번째 catch가 실행하지 않았던 것이다.</li>
</ol>

<p>여기서 두번째 chain을 실행하고 싶다면, throw를 던지는 것이다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">1st catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">);</span>
    <span class="k">throw</span> <span class="nx">e</span><span class="p">;</span>
  <span class="p">})</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">2nd catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<h3 id="then을-활용한-catch">then을 활용한 catch</h3>

<p>then 구문에는 2가지 파라미터를 보낼 수 있다.</p>

<ul>
  <li>onfullfilled : then에서 성공했을때 실행하는 함수</li>
  <li>onrejected : then에서 실패했을때 실행하는 함수</li>
</ul>

<p><img src="https://user-images.githubusercontent.com/26196090/74639147-b6220c00-51b0-11ea-827c-67de30e8a2b2.png" /></p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  <span class="p">.</span><span class="nx">then</span><span class="p">(</span>
    <span class="p">()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">done!!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span>
    <span class="nx">e</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">1st catch in Then</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">);</span>
    <span class="p">}</span>
  <span class="p">)</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">2nd catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><img width="226" alt="" src="https://user-images.githubusercontent.com/26196090/74639619-8e7f7380-51b1-11ea-8204-e8ac7ced83f3.png" /></p>

<p>then에 의해 작성된 cath가 실행되는 것을 볼 수 있다.<br />
여기서도 두번째 catch는 실행되지 않았다. 즉, then에게 주어진 일이 정상적으로 실행되지 않았을때 발생하기 때문이다.</p>

<p>두번째 catch가 실행하도록 상황을 가정한다면, 다음과 같이 할 수 있다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">)</span>
  <span class="p">.</span><span class="nx">then</span><span class="p">(</span>
    <span class="p">()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">done!!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span>
    <span class="nx">e</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">1st catch in Then</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">);</span>
      <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">'</span><span class="s1">throw in Then</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">}</span>
  <span class="p">)</span>
  <span class="p">.</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">2nd catch</span><span class="dl">'</span><span class="p">,</span> <span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><img width="269" alt="" src="https://user-images.githubusercontent.com/26196090/74639976-27ae8a00-51b2-11ea-8b52-265b64113a52.png" /></p>

<h2 id="async--await의-예외">async / await의 예외</h2>

<p>async의 동작을 알아보자</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">return</span> <span class="dl">'</span><span class="s1">done!</span><span class="dl">'</span><span class="p">;</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">result</span><span class="p">);</span>
</code></pre></div></div>

<p><img width="257" alt="" src="https://user-images.githubusercontent.com/26196090/74640298-a4d9ff00-51b2-11ea-9be6-cf319420df24.png" /></p>

<p>async의 결과는 promise의 인스턴스가 리턴된다.<br />
이것은 promise를 생성한 것과 동일한 결과값을 보여준다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">return</span> <span class="dl">'</span><span class="s1">done!</span><span class="dl">'</span><span class="p">;</span>
<span class="p">}</span>

<span class="kd">function</span> <span class="nx">myPromiseFunc</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">resolve</span><span class="p">(</span><span class="dl">'</span><span class="s1">done!!</span><span class="dl">'</span><span class="p">));</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
<span class="kd">const</span> <span class="nx">result2</span> <span class="o">=</span> <span class="nx">myPromiseFunc</span><span class="p">();</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">result</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">result2</span><span class="p">);</span>
</code></pre></div></div>

<p><img width="272" alt="" src="https://user-images.githubusercontent.com/26196090/74640624-35184400-51b3-11ea-816d-731ef9341181.png" /></p>

<p>즉, async는 promise의 resolve에 해당한다고 보면 된다.</p>

<p>async에서 reject를 발생하고 싶다면, 일반 함수에서 error을 발생한 것과 같은 throw를 걸어주면 promise에서 reject와 같은 동일한 결과를 얻을 수 있다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">throw</span> <span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">;</span>
<span class="p">}</span>

<span class="kd">function</span> <span class="nx">myPromiseFunc</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!!</span><span class="dl">'</span><span class="p">));</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
<span class="kd">const</span> <span class="nx">result2</span> <span class="o">=</span> <span class="nx">myPromiseFunc</span><span class="p">();</span>

<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">result</span><span class="p">);</span>
<span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="nx">result2</span><span class="p">);</span>
</code></pre></div></div>

<p><img width="306" alt="" src="https://user-images.githubusercontent.com/26196090/74640894-aeb03200-51b3-11ea-857c-7367cee8beb3.png" /></p>

<p>여기서 중요한 것은 promise는 promise를 생성하는 과정에서 reject를 발생시켰다.<br />
하지만 async함수에서는 동기적으로 실행하는 함수에서 예외를 발생하는 방법과 동일하게, throw를 이용해 reject를 발생시켰다.</p>

<p>그렇다면, 현재는 Uncaught인 throw를 잡는 방법은 무엇일까?<br />
promise와 동일하다.<br />
왜냐하면, 리턴되는 값이 promise와 동일하기 때문이다. 그래서 그걸 잡는 방법도 promise와 동일하다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">throw</span> <span class="dl">'</span><span class="s1">error!</span><span class="dl">'</span><span class="p">;</span>
<span class="p">}</span>

<span class="kd">function</span> <span class="nx">myPromiseFunc</span><span class="p">()</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">error!!</span><span class="dl">'</span><span class="p">));</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">().</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">));</span>
<span class="kd">const</span> <span class="nx">result2</span> <span class="o">=</span> <span class="nx">myPromiseFunc</span><span class="p">().</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">));</span>
</code></pre></div></div>

<p><img width="161" alt="" src="https://user-images.githubusercontent.com/26196090/74641470-b4f2de00-51b4-11ea-9593-c93da6b3660c.png" /></p>

<h3 id="await">await</h3>

<p>async에서는 await함수를 쓸 수 있다. await은 async 함수 내부에서만 사용할 수 있다.</p>

<p>await는 무엇을 하는 녀석인가?<br />
promise를 기다릴 수 있는 녀석이다.<br />
즉, promise가 완전히 fullfilled 되거나 또는 rejected 될때까지 기다린다는 의미이다.</p>

<p>아래 구문을 보자.<br />
wait promise 함수를 호출하는 과정을 async가 어떻게 처리하는지 알아보자.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="nx">resolve</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait function</span><span class="dl">'</span><span class="p">);</span>
      <span class="nx">resolve</span><span class="p">(</span><span class="dl">'</span><span class="s1">done!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p>현재 async 함수는 동기적인 실행이 되고 있어, 첫번째 날짜를 출력하고, wait을 리턴하고 바로 다음 날짜를 출력하고 있다.</p>

<p><img width="475" alt="스크린샷 2020-02-17 오후 6 52 57" src="https://user-images.githubusercontent.com/26196090/74642685-cccb6180-51b6-11ea-9250-d763e9868335.png" /></p>

<p>async의 await을 사용해보자.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">(</span><span class="nx">resolve</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait function</span><span class="dl">'</span><span class="p">);</span>
      <span class="nx">resolve</span><span class="p">(</span><span class="dl">'</span><span class="s1">done!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p>async 안에서 await이 완료될 때까지 다음이 실행되지 않는 것을 볼 수 있다.</p>

<p><img src="https://user-images.githubusercontent.com/26196090/74643656-6cd5ba80-51b8-11ea-9469-5e7dcbb4f4fa.gif" /></p>

<p>이 상황을 reject 하는 상황으로 바꿔보자.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait function</span><span class="dl">'</span><span class="p">);</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait error!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p>Uncaught 결과값이 나온다. 이 결과는 promise에서 reject된 결과를 제대로 잡지 못했다는 얘기다.</p>

<p><img src="https://user-images.githubusercontent.com/26196090/74645551-84fb0900-51bb-11ea-8bc7-d0c8df5eccb4.gif" alt="" /></p>

<p>myAsyncFun함수에서는 promise를 await를 이용해 기다리도록 했다.<br />
fullfilled되면 자연스럽게 그 다음줄이 실행되어, resolve된게 await의 값으로 쓰이지만,<br />
만약에 reject된다면? 그러면 throw가 된다.<br />
reject할때 들어있는 값이 throw하게 된다.<br />
throw했으니까 이를 잡는 방법은 try, catch가 된다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait error!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
  <span class="p">}</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p><img width="360" alt="" src="https://user-images.githubusercontent.com/26196090/74645888-1d918900-51bc-11ea-8db1-74e8120fff57.png" /></p>

<p>try, catch를 하지않았다면, 두번째 날짜를 출력하는 구문이 실행되지 않았을 것이다.</p>

<h3 id="awaitcatch의-사용">await.catch()의 사용</h3>

<p>만약, catch를 쓰면 어떨까?<br />
catch로 사용하면 try, catch문을 사용했을때와 동일한 결과를 보여준다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait error!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">).</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
  <span class="p">});</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p><img width="336" alt="" src="https://user-images.githubusercontent.com/26196090/74646760-cb516780-51bd-11ea-9e9c-00555cdf9121.png" /></p>

<p>하지만, 이를 리턴하는 객체 정보에는 차이가 있다.<br />
result 변수에 담아 출력해보면 undefined가 찍힌다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait error!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">).</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
  <span class="p">});</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="dl">'</span><span class="s1">result: </span><span class="dl">'</span><span class="p">,</span> <span class="nx">result</span><span class="p">);</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">();</span>
</code></pre></div></div>

<p><img width="356" alt="" src="https://user-images.githubusercontent.com/26196090/74646476-4a926b80-51bd-11ea-8fea-428e161b196b.png" /></p>

<p>wait()에서 resolve였다면, myAsyncFun()의 result에 값을 잘 받아와 찍히는데,<br />
reject를 하면 undefined가 찍힌다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="nx">resolve</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait resolved!!</span><span class="dl">'</span><span class="p">);</span>
</code></pre></div></div>

<p><img width="346" alt="스크린샷 2020-02-17 오후 7 53 53" src="https://user-images.githubusercontent.com/26196090/74647581-3ea7a900-51bf-11ea-8170-987416a6d091.png" /></p>

<p>이 얘기는 await가 기다리는 promise는 wait()의 promise가 아니라,<br />
catch를 통해서 리턴된 promise 값을 await하고 있는 것이다.<br />
resolve라면 정상적으로 잘 출력된다. 하지만, catch에서는 어떤 값도 리턴하지 않기때문에 undefined가 찍히게 된다.<br />
리턴을 해줘야 catch의 resolve값이 된다.</p>

<p><img src="https://user-images.githubusercontent.com/26196090/74647256-b1fceb00-51be-11ea-8f6a-b87b123483c4.jpg" width="422" /></p>

<h3 id="async-함수-내의-에러-대응">async 함수 내의 에러 대응</h3>

<p>async 함수 안에서 문법 등 오류가 발생했을때는 어떻게 해야할까?<br />
아래 예제에서 async 구문에 consssole.log로 구문 오류가 발생했다.
async 오류여서 try, catch로 하면, Uncaught 에러가 발생한다.
왜냐하면, async는 promise를 리턴하기때문에 try, catch가 아닌 catch로 에러를 잡아야 한다.</p>

<div class="language-javascript highlighter-rouge"><div class="highlight"><pre class="highlight"><code><span class="kd">function</span> <span class="nx">wait</span><span class="p">(</span><span class="nx">sec</span><span class="p">)</span> <span class="p">{</span>
  <span class="k">return</span> <span class="k">new</span> <span class="nb">Promise</span><span class="p">((</span><span class="nx">resolve</span><span class="p">,</span> <span class="nx">reject</span><span class="p">)</span> <span class="o">=&gt;</span> <span class="p">{</span>
    <span class="nx">setTimeout</span><span class="p">(()</span> <span class="o">=&gt;</span> <span class="p">{</span>
      <span class="nx">reject</span><span class="p">(</span><span class="dl">'</span><span class="s1">wait error!!</span><span class="dl">'</span><span class="p">);</span>
    <span class="p">},</span> <span class="nx">sec</span> <span class="o">*</span> <span class="mi">1000</span><span class="p">);</span>
  <span class="p">});</span>
<span class="p">}</span>

<span class="k">async</span> <span class="kd">function</span> <span class="nx">myAsyncFun</span><span class="p">()</span> <span class="p">{</span>
  <span class="nx">consssole</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
  <span class="k">try</span> <span class="p">{</span>
    <span class="k">await</span> <span class="nx">wait</span><span class="p">(</span><span class="mi">3</span><span class="p">);</span>
  <span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
    <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
    <span class="k">throw</span> <span class="k">new</span> <span class="nb">Error</span><span class="p">(</span><span class="dl">'</span><span class="s1">error 발생</span><span class="dl">'</span><span class="p">);</span>
  <span class="p">}</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">log</span><span class="p">(</span><span class="k">new</span> <span class="nb">Date</span><span class="p">());</span>
<span class="p">}</span>

<span class="c1">// async는 promise를 리턴하기 때문에 catch를 이용해 에러 대응을 해야한다.</span>
<span class="kd">const</span> <span class="nx">result</span> <span class="o">=</span> <span class="nx">myAsyncFun</span><span class="p">().</span><span class="k">catch</span><span class="p">(</span><span class="nx">e</span> <span class="o">=&gt;</span> <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">));</span>

<span class="c1">// try, catch로 하면, Uncaught가 됨</span>
<span class="k">try</span> <span class="p">{</span>
  <span class="nx">myAsyncFun</span><span class="p">();</span>
<span class="p">}</span> <span class="k">catch</span> <span class="p">(</span><span class="nx">e</span><span class="p">)</span> <span class="p">{</span>
  <span class="nx">console</span><span class="p">.</span><span class="nx">error</span><span class="p">(</span><span class="nx">e</span><span class="p">);</span>
<span class="p">}</span>
</code></pre></div></div>

<p><img width="517" alt="" src="https://user-images.githubusercontent.com/26196090/74652978-8bdd4800-51ca-11ea-91f2-d9b77234ed11.png" /></p>

<h2 id="정리">정리</h2>

<ul>
  <li>async 내에서의 promise 처리는 try, catch로 한다.</li>
  <li>async로 리턴된 값은 promise이기 때문에, async 이후에 발생한 에러는 catch로 대응한다.</li>
</ul>

</article>



<section class="tags">
  <strong>Tags:</strong> <a href="/tag/javascript">javascript</a>,&nbsp;<a href="/tag/js">js</a>,&nbsp;<a href="/tag/try">try</a>,&nbsp;<a href="/tag/catch">catch</a>
</section>



<section class="rss">
  <p class="rss-subscribe text"><strong>Subscribe <a href="/feed.xml">via RSS</a></strong></p>
</section>

<section class="share">
  <span>Share: </span>
  
    
    
    
    
    
    
    
    
  
</section>




</div>
</div>

    </div>

    <footer class="site-footer">

  <div class="wrapper">

    <h3 class="footer-heading">vlueviolet's blog</h3>

    <div class="site-navigation">

      <p><strong>Site Map</strong></p>
      <ul class="pages">
				
	
	<li class="nav-link"><a href="/about/">About</a>
	

	

	

	
	<li class="nav-link"><a href="/posts/">Posts</a>
	

	
	<li class="nav-link"><a href="/typography/">Typography</a>
	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	


      </ul>
    </div>

    <div class="site-contact">

      <p><strong>Contact</strong></p>
      <ul class="social-media-list">
        <li>
          <a href="mailto:">
            <i class="fa fa-envelope-o"></i>
            <span class="username"></span>
          </a>
        </li>

        
          
          <li>
            <a href="https://github.com/vlueviolet" title="Fork me on GitHub">
              <i class="fa fa-github"></i>
              <span class="username">vlueviolet</span>
            </a>
          </li>
          
        

      </ul>
    </div>

    <div class="site-signature">
      <p class="rss-subscribe text"><strong>Subscribe <a href="/feed.xml">via RSS</a></strong></p>
      <p class="text"># A simple yet classy theme for your Jekyll website or blog.
</p>
    </div>

  </div>

</footer>

<!-- Scripts -->
<script src="//code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/lightbox2/2.11.1/js/lightbox.min.js"></script>
<script src="//unpkg.com/popper.js@1"></script>
<script src="//unpkg.com/tippy.js@5"></script>

<script type="text/javascript">
$(document).ready(function() {
  // Default syntax highlighting
  hljs.initHighlightingOnLoad();

  // Header
  var menuToggle = $('#js-mobile-menu').unbind();
  $('#js-navigation-menu').removeClass("show");
  menuToggle.on('click', function(e) {
    e.preventDefault();
    $('#js-navigation-menu').slideToggle(function(){
      if($('#js-navigation-menu').is(':hidden')) {
        $('#js-navigation-menu').removeAttr('style');
      }
    });
  });

	// Enable tooltips via Tippy.js
	if (Array.isArray(window.tooltips)) {
		window.tooltips.forEach(function(tooltip) {
			var selector = tooltip[0];
			var config = tooltip[1];
			tippy(selector, config);
		})
	}
});

</script>






  </body>

</html>
